[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 5000
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
base = "dark"
backgroundColor = "#0B0D10"
secondaryBackgroundColor = "#13161B"
textColor = "#E8E0D0"
font = "sans serif"
